[package]
name = "maat_graphics"
version = "0.3.0"
authors = ["Lilith645 <lilith@inet-sys.com>"]

[dependencies]
gltf = "0.11.1"
cgmath = "0.16.1"
image = "*"
vulkano = "0.10.0"
vulkano-shader-derive = "0.10.0"
vulkano-win = "0.10.0"
winit = "0.17.2"
base64 = "*"

[target.'cfg(target_os = "macos")'.dependencies]
cocoa = "0.13"
objc = "0.2.2"
metal-rs = "0.6"
