[package]
name = "maat_graphics"
version = "0.3.0"
authors = ["Lilith645 <lilith@inet-sys.com>"]

[dependencies]
gltf = "0.11.1"
cgmath = "0.16.1"
image = "*"
vulkano = "0.11.0"
vulkano-shaders = "0.11.0"
vulkano-win = "0.11.0"
winit = "0.18.0"
base64 = "*"

[target.'cfg(target_os = "macos")'.dependencies]
metal = "0.13"
cocoa = "0.18"
objc = "0.2.2"
