[package]
name = "maat_graphics"
version = "0.2.1"
authors = ["Lilith645 <lilith@inet-sys.com>"]

[dependencies]
gltf = "0.11.1"
cgmath = "*"
gl = "0.6.0"
image = "*"
vulkano = "0.9.0"
vulkano-shader-derive = "0.9.0"
vulkano-win = "0.9.0"
winit = "0.16.0"
glutin = "0.17.0"
base64 = "*"

[target.'cfg(target_os = "macos")'.dependencies]
cocoa = "0.13"
objc = "0.2.2"
metal-rs = "0.6"
