[package]
name = "maat_engine"
version = "0.2.0"
authors = ["Lilith645 <lilith@inet-sys.com>"]

[dependencies]
cgmath = "*"
gl = "0.6.0"
image = "*"
vulkano = "0.9.0"
vulkano-shader-derive = "0.9.0"
vulkano-win = "0.9.0"
winit = "0.8.1"
glutin = "0.10.0"
piston-opengex = "*"
piston_meta = "*"
piston_meta_search = "*"
range = "*"
nom = "^3.2"

[target.'cfg(target_os = "macos")'.dependencies]
cocoa = "0.13"
objc = "0.2.2"
metal-rs = "0.6"
