[package]
name = "maat_graphics"
version = "0.6.0"
authors = ["Lilith645 <lilith@inet-sys.com>"]
edition = '2018'

[dependencies]
vk = { version = "0.4.0", package = "vk-sys" }
gltf = "0.11.3"
cgmath = "0.17.0"
image = "0.20.1"
winit = "0.18.0"
base64 = "*"
shared_library = "0.1.7"
lazy_static = "1.2.0"
libc = "0.2.44"


[target.'cfg(all(unix, not(target_os = "android"), not(target_os = "macos")))'.dependencies]
wayland-client = "=0.21.7"

[target.'cfg(target_os = "macos")'.dependencies]
metal = "0.13"
cocoa = "0.18"
objc = "0.2.2"
moltenvk_deps = "0.1.0"
