[package]
name = "maat_engine"
version = "0.1.0"
authors = ["Lilith645 <lilith@inet-sys.com>"]

[dependencies]
cgmath = "0.15.0"
gl = "0.6.0"
image = "*"
vulkano = "0.7.2"
vulkano-shader-derive = "0.7.2"
vulkano-win = "0.7.2"
winit = "0.8.1"
glutin = "0.10.0"
piston-opengex = "*"
piston_meta = "*"
piston_meta_search = "*"
range = "*"

[target.'cfg(target_os = "macos")'.dependencies]
cocoa = "0.9"
objc = "0.2"
metal-rs = "0.4.3"
